---
abstract: 'Get Arsenal FC ticket information for forthcoming matches'
author:
  - 'Andrew Jones <andrew@arjones.co.uk>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  FindBin: 0
  HTTP::Online: 0
  Net::Ping: 2.33
  Test::Deep: 0
  Test::More: 0.88
  aliased: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-ArsenalFC-TicketInformation
requires:
  Exporter: 0
  HTML::TreeBuilder::XPath: 0
  LWP::Simple: 0
  Object::Tiny: 0
  constant: 0
  perl: v5.10.1
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/andrewrjones/perl5-WWW-ArsenalFC-TicketInformation/issues
  homepage: https://github.com/andrewrjones/perl5-WWW-ArsenalFC-TicketInformation
  repository: https://github.com/andrewrjones/perl5-WWW-ArsenalFC-TicketInformation.git
version: 1.123160
